// Ojhan Ardalan AD3 CISP 401 Fall 2018
// Multiply.java
import java.util.*
public class Multiply {
	static Random r = new Random(); //creates a new Random object
	static Scanner scan = new Scanner(System.in); //creates a new Scanner object
	private static int a, b, totalQuestions, correct; //initializes the variables needed
	private static int[][] questions = new int[100][5]; //creates a 2D array to store the questions and answers
	
	public static void quiz() { //the quiz method
		int answer = 0; //initializes the answer variable 
		while(true) { //loops until the user wants to quit
			createQuestion(); //calls the createQuestion method
			answer = scan.nextInt(); //sets the user's answer
			
			if (answer == -1) //will close the loop if the user inputs -1
				break;
			
			checkResponse(answer); //runs the checkResponse method
			
			totalQuestions++; //increases the total questions by one
		} 
	}

	public static void createQuestion() { //the createQuestion method
		a = r.nextInt(10); //sets a random number to a
		b = r.nextInt(10); //sets a random number to b
		System.out.printf("How much is %d times %d? \nEnter your answer (-1 to exit): ", a, b); //asks the user what the product of the two random numbers are
	}
	
	public static String createResponse(boolean x) { //the createResponse method
		switch(r.nextInt(4)){ //a switch case with four options which is randomly chosen 
		case 0:
			return x ? "Very Good!" : "No. Please try again.";
		case 1:
			return x ? "Excellent!" : "Wrong. Try once more";
		case 2:
			return x ? "Nice work!" : "Don't give up!";
		case 3:
			return x ? "Keep up the good work!" : "No. Keep trying.";	
		}
	return null;	
	}
	
	public static void checkResponse(int ans) { //the checkResponse method
		System.out.println(createResponse(a * b == ans)); //calls and prints the createResponse method with the user's answer
		if (a*b == ans) //will add one to the total correct if the answer is correct
			correct++;
		else 
			System.out.println("The correct answer was: " + a * b); //prints the error if the answer is wrong
		System.out.println();
		
		questions[totalQuestions][0] = a; //stores the question, answer, and user's input in the 2D array
		questions[totalQuestions][1] = b;
		questions[totalQuestions][2] = a * b;
		questions[totalQuestions][3] = ans;
}
		
	public static void printQuestionResult() { //the printQuestionResult method
		System.out.println("The questions generated by the system are:");
		for(int j = 0; j < totalQuestions; j++) { //will loop through the 2D array and print its data
			System.out.printf("\n%d * %d = %d ", questions[j][0], questions[j][1], questions[j][2]); 
			if (questions[j][3] != questions[j][2]) //print print the correct answer if one of the answers are incorrect
				System.out.print("Your answer was " + questions[j][3] + ", which is incorrect.");
		}
		System.out.println("\n---------------------------------------------------------------\n");
		System.out.printf("You had %d questions and got %d questions correct.\n", totalQuestions, correct);
		System.out.println(createResponse((double)correct/totalQuestions > .66)); //checks to see if the user got more than 2/3rds of the questions right

	}
}
